### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by leonardltk** [ctralie/GraphDitty#9]
Hi, can you list down the exact versions of your dependencies?
in particular, 

- python2.? or python3.? 
- librosa==?
- scipy==?

I am using python 3.6, and at one of the later versions of librosa==0.7.0, it is required for scipy>=1.0.0.

When i ran the program, i met into the following error
```
Traceback (most recent call last):
  File "SongStructure.py", line 300, in <module>
    saveResultsJSON(opt.filename, res['times'], res['Ws'], opt.neigs, opt.jsonfilename, opt.diffusion_znormalize)
  File "/data3/lootiangkuan/AudioHashing/QbH/v2_GraphDitty/SongStructureGUI.py", line 151, in saveResultsJSON
    Results['W'] = getBase64PNGImage(WOut, 'magma_r', logfloor_quantile=0.01)
  File "/data3/lootiangkuan/AudioHashing/QbH/v2_GraphDitty/SongStructureGUI.py", line 58, in getBase64PNGImage
    scipy.misc.imsave("temp.png", C)
AttributeError: module 'scipy.misc' has no attribute 'imsave'
```
According to [this question](https://stackoverflow.com/questions/19991665/my-scipy-misc-module-appears-to-be-missing-imsave) , it seems i require scipy==0.17.0

**Comment by leonardltk** [comment]
According to [this scipy documentation](https://docs.scipy.org/doc/scipy-1.1.0/reference/generated/scipy.misc.imsave.html) , it seems you should replace 

`scipy.misc.imsave`
with
`imageio.imwrite`
instead.

But still, it will be good to know what are the exact dependencies you have to reproduce the code.

**Comment by ctralie** [comment]
Thank you for bringing this to my attention!  I've fixed this and added a requirements.txt file.  If you're going to simply run SongStructure.py to generate your own examples, then that should be sufficient.  If, on the other hand, you're going to try to replicate all of the results from my paper, well then we may run into some more issues.  We were using some CREMA features in the paper that required a whole mess of different Python and librosa versions.  So that will take some more effort.  But hopefully SongStruture.py is enough for you for now
